version: "3"
services:
  strapi:
    image: api:latest
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DB_NAME}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASS}
    links:
      - postgres:postgres
    volumes:
      - ./:/app
    ports:
      - "1337:1337"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
